### ISSUE TITLE
Docs: Read-the-docs theme is barely readable in dark mode

### ISSUE THREAD

**Issue by oleg-nenashev** [SwissDataScienceCenter/renku#2869] opened 2022-12-19 21:51 UTC
**Describe the bug**
My phone browser runs in the dark mode by default. In this mode, the text color does not change due to enforced CSS (from what I understood after a quick glance through code). It impacts the readability

**Link to project**
N/A. Root page like https://renku.readthedocs.io/en/latest/ works for the reproduction

**To Reproduce**
1. Switch your browser to the dark mode
2. Go to https://renku.readthedocs.io/en/latest/

**Expected behavior**
All text is readable

**Screenshots and/or execution output**

![image](https://user-images.githubusercontent.com/3000480/208531067-c4d5f1fe-13bc-48de-ae43-b8af77de5753.png)

**Run environment (please complete the following information):**

 - browser: Chrome Latest, Chrome from Android Latest

**Comment by rokroskar** [comment] 2023-01-25 15:37
Thanks for pointing this out @oleg-nenashev !

**Comment by ciyer** [comment] 2023-01-26 10:44
Thanks for this bug report!

I investigated, and though it appears to be so, the problem is not actually related to dark mode. When the viewport width becomes smaller than 1100px, the background for the side bar becomes the background for all the content. I have created an issue to fix this in the sphinx theme: https://github.com/SwissDataScienceCenter/renku-sphinx-theme/issues/16

**Comment by oleg-nenashev** [comment] 2023-01-26 11:08
Thanks for the patch! Indeed, I spent quite a lot of time surfing the site
on the mobile, should have checked the laptop widescreen mode too. The
latter uses the light scheme by default though

**Comment by rokroskar** [comment] 2023-09-26 16:01
This was fixed in https://github.com/SwissDataScienceCenter/renku-sphinx-theme/pull/19

**Closed by rokroskar** 2023-09-26 16:01 UTC
Labels: kind/bug
