### ISSUE TITLE
Error trying to launch new JupyterLab server

### ISSUE THREAD

**Issue by dominikwerder** [SwissDataScienceCenter/renku#581] opened 2019-06-11 12:48 UTC
On `renkulab.io` it's currently not possible to launch a new JupyterLab server.

Browser: Chrome latest stable.
Symptom: Infinite busy spinner, 404 errors on console.

**Comment by fgeorgatos** [comment] 2019-06-11 13:11
@dominikwerder : could you please try to reproduce, keeping a record of exact timings?

fyi. from our end, it seems we cannot reproduce it and notebooks come up as normal.

**Comment by dominikwerder** [comment] 2019-06-11 13:31
As soon as I click the "Launch Server" button, I see a 404 for this URL:

```
https://renkulab.io/api/projects/551/graph/webhooks/validation
```

Not sure what you mean by exact timings? The 404 appears after the click on the button, no later then some hundreds ms. Hope that helps.

**Comment by rokroskar** [comment] 2019-06-11 14:08
@dominikwerder thanks for reporting this - it appears that you have hit a bug on project creation. Your project is empty which probably means that the initialization step never completed. You could either a) delete the project using the gitlab UI and create it again or b) initialize the project using the command line renku on your machine and push to the master branch.

**Comment by rokroskar** [comment] 2019-06-11 15:10
@ableuler here is another case of an empty project being created - do you remember what the problem was a few weeks (months?) back when this happened?

**Comment by ableuler** [comment] 2019-06-12 11:44
> @ableuler here is another case of an empty project being created - do you remember what the problem was a few weeks (months?) back when this happened?

I have some vague memory of this but I do not remember any exact reason for the creation of empty projects. Would be helpful to see the response of the HTTP call which should create the first commit. I've just tried and for me project creation seems to work fine. 
Could it have been a network interruption during project creation, such that the project creation got through but not the subsequent commit)?

**Comment by rokroskar** [comment] 2019-06-12 11:47
> Could it have been a network interruption during project creation, such that the project creation got through but not the subsequent commit)?

I think this is what we eventually concluded without any concrete resolution because it's very hard to reproduce.

**Comment by ableuler** [comment] 2019-06-12 11:50
👍 This is actually another reason for moving project creation (rendering templates etc) away from the UI. For the UI it should be one single POST request which either goes through or fails.

Can we thus close this issue?

**Comment by rokroskar** [comment] 2019-06-12 11:51
I want to make sure @dominikwerder is able to get a project going before we close it.

**Comment by dominikwerder** [comment] 2019-06-13 05:57
On a second attempt it workes, again with Chrome 75.0.
I can launch a jupyterlab server and connect to it.

**Comment by rokroskar** [comment] 2019-06-13 06:01
Great, I'll close this issue but if the problem reappears please reopen it.

**Closed by rokroskar** 2019-06-13 06:01 UTC
Labels: user
