### ISSUE TITLE
Underscore in username causes the image build to fail

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#1128] opened 2020-05-27 10:19 UTC
Underscores `_` seem to be allowed in email usernames, they are not, however, allowed in docker image names. If a username has underscores, the image build will fail. We should handle this somehow but it's not obvious how if the user is allowed to pick that username.

**Comment by ableuler** [comment] 2020-10-04 07:26
I can not reproduce this problem. Underscores in docker image names seem to be accepted, try
```
docker pull registry.renkulab.io/test_unserscore/public_test:d24424b
```
for example.

**Comment by rokroskar** [comment] 2020-10-04 18:59
Did you try changing your username?

**Comment by rokroskar** [comment] 2020-10-04 19:02
This definitely failed in May for a student in the SIB course. It's possible something has changed in the meantime in the docker registry and/or gitlab

**Comment by ableuler** [comment] 2020-10-05 08:09
Closing this issue since the problem can not be reproduced at the moment. Let's keep it in the back of our heads though and reopen the issue if we see a similar problem.

**Closed by ableuler** 2020-10-05 08:09 UTC
Labels: bug
