### ISSUE TITLE
post-init issue

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku#3393] opened 2023-11-30 14:46 UTC
**Describe the bug**
I believe that the project ./post-init.sh script is not always invoked on start up as it should be.

And I suspect that this is because the [/entrypoint.sh](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/fa131102e63f67f6ab46bc25ad4ba44c59b5e91a/docker/py/entrypoint.sh#L33-L35) attempts to execute the script before the git clone completes.

**To Reproduce**
1. Create a post-init.sh in the project that writes to a log file when it is executed, e.g. `echo 'started' >> /tmp/post-init.log`
2. Commit and push the changes
3. Start the project
4. Check the log file
5. Repeat if necessary

Since this could be is a race condition, you may need to artificially make the git clone slower, e.g. by adding files to emulate larger projects.

**Expected behavior**
A log file should be there.

**Screenshots and/or execution output**
If applicable, add screenshots and/or execution output to help explain your problem.

**Run environment (please complete the following information):**
 - renkulab browser
 - Jupyterlab: renku/renkulab-py:3.10-0.18.1
 - renku-python version: RENKU_VERSION=2.7.0
 - browser: firefox, but shouldn't matter

**Additional context**
* This issue happened during a class, when tens of students started their renkulab sessions simultaneously. The way around is to add a [/post-init.sh](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/fa131102e63f67f6ab46bc25ad4ba44c59b5e91a/docker/py/entrypoint.sh#L28-L30) that spawns a background process that waits up to a reasonable amount of time for the presence of the post-init.sh script, which is expected to be present in this project. 
* The [part](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/fa131102e63f67f6ab46bc25ad4ba44c59b5e91a/docker/py/entrypoint.sh#L38-L43) that copies the authorized ssh keys could also be affected

**Comment by rokroskar** [comment] 2024-02-22 13:00
@erbou I don't think it's possible for the script to run before git clone because that runs in an init container, which must complete before the main container starts. I use the `post-init.sh` [here](https://renkulab.io/projects/rok.roskar/rclone-sync-demo/files/blob/post-init.sh) and it works as advertised. Could you post a link to a project where it isn't working as expected?

**Comment by rokroskar** [comment] 2024-06-13 15:49
@erbou I'm closing this for now - not sure if the problem is still there, feel free to reopen if that is the case.

**Closed by rokroskar** 2024-06-13 15:49 UTC
Labels: kind/bug, status/triage
