### ISSUE TITLE
Http error 404 when following a project link without being logged in

### ISSUE THREAD

**Issue by gmartinezmirai** [SwissDataScienceCenter/renku#730] opened 2020-01-27 13:40 UTC
**Bug description**
Following a link to a private or internal project results in a 404 error unless the user is logged in.

Affects non-public projects, in line with the [project visibility documentation](https://renkulab.io/gitlab/help/public_access/public_access). The error screen also advices to login in an info panel. However, one could consider this a bug since it could be expected to be directed to the login page instead of throwing an error in this situation.

**Tested on project**
https://renkulab.io/projects/gustavo.martinez/mirailabs-2-0/

**Steps to reproduce**:
1. Logout from Renkulab
2. Follow the link https://renkulab.io/projects/gustavo.martinez/mirailabs-2-0/
3. The following error is obtained:
![image](https://user-images.githubusercontent.com/9316125/73178099-d827f180-4110-11ea-87aa-6da1e90fd37b.png)

**Expected behavior**
When I perform steps 1 and 2 above, I would expect to be directed to the login page:
![image](https://user-images.githubusercontent.com/9316125/73178903-81bbb280-4112-11ea-9e13-d12e42fef7b5.png)

After logging in, I should either:
a) be directed to the project page, if I am authorized, or
b) be directed to an error page, if I am not authorized. The error page should inform me that I am not authorized to access the project, and ideally also offer me the possibility request access or contact the project owner.

**Comment by lorenzo-cavazzi** [comment] 2020-01-27 14:42
Hello @gmartinezmirai  and thanks for reporting.
Showing a generic 404 page here is the intended behavior and the reason is to avoid leaking information about private repositories.
We see the same behavior in many popular repository managers (e.g. GitHub)

**Comment by gmartinezmirai** [comment] 2020-01-27 16:12
Hello @lorenzo-cavazzi, many thanks for the prompt response.
I understand the rationale for the 404 page, but the alternative suggested does not necessarily pose a risk of information leaking. If the login page is interposed irrespective of the existence or not of the resource requested, i.e., as long as the url starts with https://renkulab.io/projects/, this mitigates the risk of leaking.

**Comment by lorenzo-cavazzi** [comment] 2020-01-28 10:19
I see your point and I agree it may be useful in specific circumstances (e.g. people who bookmarked a project). On the other hand, we are trying to support anonymous navigation. The idea is to avoid automatically requiring a login whenever it's possible so that users can initially browse public content without being forced to create a user.

In this picture, I believe a `404` page with a short explanation fits better than redirecting automatically to the login page to end up in the same `404` page.

Thanks to this ticket, I noticed that the UI shows to anonymous users a slightly different interaction in the `404` page compared to others (see the two screenshots below). Adding the `Log in` button also there should make life a bit easier for users who expect to be logged in while keeping the current flow unchanged.

![Screenshot_20200128_110557](https://user-images.githubusercontent.com/43481553/73254721-3dd2b700-41bf-11ea-9ea7-81b5ac317f90.png)

![Screenshot_20200128_110642](https://user-images.githubusercontent.com/43481553/73254893-88ecca00-41bf-11ea-8d1d-041038a50c28.png)

**Comment by lorenzo-cavazzi** [comment] 2020-02-12 14:22
The next release will have a slightly different `404` page SwissDataScienceCenter/renku-ui#759

Despite not being in line with what @gmartinezmirai initially suggested, we hope to make it more clear for non-logged users that they should try to log-in without forcing it. This allows anonymous users to keep on browsing https://renkulab.io/projects/* pages.

I am closing this issue for now. Please feel free to re-open it later if you fell the current solution is not enough.

**Closed by lorenzo-cavazzi** 2020-02-12 14:22 UTC
Labels: user
