### ISSUE TITLE
Import error for gdal _array  package 

### ISSUE THREAD

**Issue by gitanjalIthakur** [SwissDataScienceCenter/renku#1138] opened 2020-05-28 17:41 UTC
Although Gdal was installed using requirements , for reading tiff files , in notebook it was showing an import error:
ImportError: No module named '_gdal_array'
During handling of the above exception, another exception occurred:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-a232b7b6d58f> in <module>
     23     geo_fpar= fpar.GetGeoTransform()
     24     band = fpar.GetRasterBand(1)
---> 25     fpar_val = band.ReadAsArray().astype(np.float)
     26     fpar_data=fpar_val[439][1637]
     27     ####
/opt/conda/lib/python3.7/site-packages/osgeo/gdal.py in ReadAsArray(self, xoff, yoff, win_xsize, win_ysize, buf_xsize, buf_ysize, buf_type, buf_obj, resample_alg, callback, callback_data)
   2534         parameters should generally not be specified if buf_obj is specified. The array is returned"""
   2535 
-> 2536         from . import gdalnumeric
   2537 
   2538         return gdalnumeric.BandReadAsArray( self, xoff, yoff,
/opt/conda/lib/python3.7/site-packages/osgeo/gdalnumeric.py in <module>
----> 1 from osgeo.gdal_array import *
      2 from numpy import *
/opt/conda/lib/python3.7/site-packages/osgeo/gdal_array.py in <module>
     26                 fp.close()
     27             return _mod
---> 28     _gdal_array = swig_import_helper()
     29     del swig_import_helper
     30 else:
/opt/conda/lib/python3.7/site-packages/osgeo/gdal_array.py in swig_import_helper()
     18             fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])
     19         except ImportError:
---> 20             import _gdal_array
     21             return _gdal_array
     22         if fp is not None:
ModuleNotFoundError: No module named '_gdal_array'

**Comment by rcnijzink** [comment] 2020-05-29 06:04
So this was an error that occured on the jupyterlab for this repository:
https://renkulab.io/projects/gitanjali.thakur/modis_lst_fpar

The problem was that requirements.txt apparently installs the packages alphabetically in the docker, and gdal-python comes after numpy. This runs without problems as gdal installs also without numpy, but not with all functionalities.

We fixed it now by adding a second requirements.txt in the repository and changing the dockerfile:

```
FROM renku/renkulab:renku0.10.3-py3.7-0.6.2
# Uncomment and adapt if code is to be included in the image
# COPY src /code/src

# Uncomment and adapt if your R or python packages require extra linux (ubuntu) software
# e.g. the following installs apt-utils and vim; each pkg on its own line, all lines
# except for the last end with backslash '\' to continue the RUN line
#
USER root

RUN apt-get update &&\
    apt-get install -y proj-bin libgdal-dev libproj-dev gdal-bin
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal/
ENV C_INCLUDE_PATH=/usr/include/gdal/

# RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    apt-utils \
#    vim
USER ${NB_USER}



# install the python dependencies
COPY requirements.txt requirements2.txt environment.yml /tmp/
RUN conda env update -q -f /tmp/environment.yml && \
    /opt/conda/bin/pip install -r /tmp/requirements.txt && \
    /opt/conda/bin/pip install -r /tmp/requirements2.txt && \
    conda clean -y --all && \
    conda env export -n "root"
```

It works like this, but it is probably not the most elegant solution. Can we force a certain order with pip install -r requirements? I could not find how to do that...

**Comment by rokroskar** [comment] 2020-06-10 23:05
If I'm reading this correctly, the problem is not that pip installs packages alphabetically but that they are all installed at once - if a package requires another package for its _installation_ (i.e. not at runtime), it's not enough to have in the same requirements file, it needs to be installed before. This is a problem with the configuration of the gdal_array package - it needs to use a `pyproject.toml` file to correctly specify the install dependencies (see e.g. [here](https://github.com/pynbody/pynbody/blob/master/pyproject.toml)). It might be worth opening an issue with `gdal-python` but until then, installing these dependencies _before_ installing gdal-python is the only option.

I'm closing this for now as it's not really renku-related but please reopen if needed.

**Closed by rokroskar** 2020-06-10 23:05 UTC
