### ISSUE TITLE
Unable to resume session (Renku 2.0)

### ISSUE THREAD

**Issue by JohannesGawron** [SwissDataScienceCenter/renku#3851] opened 2024-12-05 17:20 UTC
**Bug description**
When I try to resume in the graphical user interface, before finishing "Loading containers status", I get the message that the session is currently stopped instead.

**Link to project**
https://renkulab.io/v2/projects/johannes.gawron/ctc-cluster-clonality

**To Reproduce**
1. Go to project
2. For the session "Python/Jupyter/VSCode for Data Science", click on ''Resume"
4. See this message:
![image](https://github.com/user-attachments/assets/c69f3a7f-38f7-4e4d-b56b-ee001e3ef57c)

**Expected behavior**
I expect the session to resume and open after a few seconds.

**Screenshots and/or execution output**
Trying to resume the session then gives me an "Unknown error"
![image](https://github.com/user-attachments/assets/a0e78ced-6b02-4456-adad-9a8ea3d05576)
and if I want to "go to the session list" I get this error:
![Screenshot 2024-12-05 at 17 45 50](https://github.com/user-attachments/assets/2a7bfda5-ff86-4ce3-a41d-bfd93509a5da)

Finally, returning to home, I end up in Renku 1.0.

**Run environment (please complete the following information):**
 - I am using renkulab in my browser.
 - The session I want to start is a Jupyterlab session named "Python/Jupyter/VSCode for Data Science". If I load the same or a different docker image for a separate session it works fine.
 - I am using Renku 2.0, release [0.61.1](https://github.com/SwissDataScienceCenter/renku/releases/tag/0.61.1)
 - Browser: I was able to reproduce the issue on Safari and Google Chrome.

**Additional context**
The session logs are unavailable unfortunately.
According to the status in the Help-section, all components are operational while I am trying this.

**Comment by leafty** [comment] 2024-12-06 09:16
Hi @JohannesGawron, thanks for reporting this. It should be fixed soon, in a upcoming release of Renku.

In the meantime, you can resume your session by accessing the project page. To do so click "<- Back" on the top-left of the session page.
![Screenshot 2024-12-06 at 10 14 08](https://github.com/user-attachments/assets/f7baf2d2-7595-42c5-aedb-eda5a815ef06)

Then click "Resume" on the session list:
![image](https://github.com/user-attachments/assets/a0251e45-1e9a-4f29-bbbe-9d9de9efb039)

**Comment by leafty** [comment] 2024-12-06 09:17
Note: duplicate of https://github.com/SwissDataScienceCenter/renku-ui/issues/3425.

**Comment by leafty** [comment] 2024-12-06 09:19
Additional note: the session is most likely affected by the issue resolved in https://github.com/SwissDataScienceCenter/amalthea/pull/778.

**Comment by JohannesGawron** [comment] 2024-12-06 10:02
@leafty Thanks for coming back to me so quickly. Just to let you know that the suggested workaround didn't work for me unfortunately. However, I will eagerly await the upcoming release.

**Comment by olevski** [comment] 2024-12-06 10:20
@JohannesGawron the release that fixes the resuming of hibernated session was just deployed on renkulab.io. So now you should be able to resume your sessions.

**Closed** 2024-12-06 11:22 UTC
Labels: kind/bug, status/triage
