### ISSUE TITLE
Port 8080 already allocated error at make start

### ISSUE THREAD

**Issue by stephan271** [SwissDataScienceCenter/renku#222] opened 2018-05-16 08:35 UTC
Following the installation instruction I get the following error on a CENT OS 7 System:

`[egli@pc11213 renga]$ make start
db uses an image, skipping
cassandra uses an image, skipping
Building keycloak
Step 1/6 : FROM jboss/keycloak-postgres:3.2.0.Final
 ---> 1aa8225b81aa
Step 2/6 : USER root
 ---> Using cache
 ---> 4f4f3d96fe41
Step 3/6 : COPY . /data
 ---> Using cache
 ---> 9f1849ad7afb
Step 4/6 : RUN chown jboss:jboss -R /data
 ---> Using cache
 ---> 6f9f0cd824be
Step 5/6 : USER jboss
 ---> Using cache
 ---> 3be78fef61af
Step 6/6 : ENTRYPOINT /data/docker-entrypoint.sh
 ---> Using cache
 ---> 089b536cf3a2
Successfully built 089b536cf3a2
graph-typesystem uses an image, skipping
graph-mutation uses an image, skipping
graph-navigation uses an image, skipping
graph-init uses an image, skipping
resource-manager uses an image, skipping
deployer uses an image, skipping
explorer uses an image, skipping
projects uses an image, skipping
storage uses an image, skipping
Building apispec
Step 1/8 : FROM python:3.6-alpine
 ---> 8eb1c554687d
Step 2/8 : RUN apk --no-cache add --update     build-base     linux-headers     python-dev
 ---> Using cache
 ---> 55631c87e74f
Step 3/8 : COPY requirements.txt /code/requirements.txt
 ---> Using cache
 ---> 3a6398f01d78
Step 4/8 : WORKDIR /code
 ---> Using cache
 ---> 8d6981c775d5
Step 5/8 : RUN pip install  --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> 2120a32aeb02
Step 6/8 : COPY swagger.py /code/swagger.py
 ---> Using cache
 ---> 7eabfaabf0ce
Step 7/8 : CMD uwsgi --http :5000 --wsgi-file swagger.py
 ---> Using cache
 ---> 56a64c9fbcef
Step 8/8 : EXPOSE 5000
 ---> Using cache
 ---> fe990c940262
Successfully built fe990c940262
swagger uses an image, skipping
ui uses an image, skipping
reverse-proxy uses an image, skipping
WARNING: The create command is deprecated. Use the up command with the --no-start flag instead.
Creating renga_db_1 ... done
Creating renga_cassandra_1 ... done
Creating renga_keycloak_1  ... done
Creating renga_graph-typesystem_1 ... done
Creating renga_graph-mutation_1   ... done
Creating renga_graph-navigation_1 ... done
Creating renga_graph-init_1       ... done
Creating renga_resource-manager_1 ... done
Creating renga_deployer_1         ... done
Creating renga_explorer_1         ... done
Creating renga_projects_1         ... done
Creating renga_storage_1          ... done
Creating renga_apispec_1          ... done
Creating renga_swagger_1          ... done
Creating renga_ui_1               ... done
Creating renga_reverse-proxy_1    ... done
Creating network "renga_default" with the default driver
Starting renga_graph-mutation_1 ... 
Starting renga_reverse-proxy_1  ... 
Starting renga_db_1             ... 
Starting renga_reverse-proxy_1    ... error
Starting renga_apispec_1          ... 
Starting renga_storage_1          ... 
Starting renga_swagger_1          ... 
Starting renga_graph-mutation_1   ... done
Starting renga_graph-navigation_1 ... 
Starting renga_db_1               ... done
Starting renga_resource-manager_1 ... done
Starting renga_apispec_1          ... done
Starting renga_storage_1          ... done
Starting renga_swagger_1          ... done
Starting renga_cassandra_1        ... done
Starting renga_graph-navigation_1 ... done
Starting renga_ui_1               ... done
Starting renga_graph-typesystem_1 ... done
Starting renga_graph-init_1       ... done
Starting renga_explorer_1         ... done
Starting renga_projects_1         ... done
Starting renga_keycloak_1         ... done
Starting renga_deployer_1         ... done

ERROR: for reverse-proxy  Cannot start service reverse-proxy: driver failed programming external connectivity on endpoint renga_reverse-proxy_1 (efbb9ebf01a1c639e887cdd362a44cbf5b70b124a7ecc6f741b2ff46bb46b145): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
make: *** [start] Error 1
[egli@pc11213 renga]$ 
`

Docker processes:
$ docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                     PORTS                                                        NAMES
1eafd74fd07c        traefik                                          "/traefik --web --..."   3 minutes ago       Created                                                                                 renga_reverse-proxy_1
dba4bb026540        rengahub/renga-ui:latest                         "python3 /app/serv..."   3 minutes ago       Up 3 minutes               0.0.0.0:32966->5000/tcp                                      renga_ui_1
92ef6fd089d5        rengahub/swagger-ui:latest                       "sh /usr/share/ngi..."   3 minutes ago       Up 3 minutes               0.0.0.0:32968->8080/tcp                                      renga_swagger_1
26f7c23402a5        renga_apispec                                    "uwsgi --http :500..."   3 minutes ago       Up 3 minutes               0.0.0.0:32963->5000/tcp                                      renga_apispec_1
f3b186a8278d        rengahub/renga-storage:latest                    "bin/docker-entryp..."   3 minutes ago       Up 3 minutes               0.0.0.0:32970->9000/tcp                                      renga_storage_1
366c37c43cb6        rengahub/renga-projects:latest                   "bin/renga-projects"     3 minutes ago       Up 3 minutes               0.0.0.0:32972->9000/tcp                                      renga_projects_1
b457e8e47b5e        rengahub/renga-explorer:latest                   "bin/renga-explorer"     3 minutes ago       Up 3 minutes               0.0.0.0:32973->9000/tcp                                      renga_explorer_1
c6deb37589ee        rengahub/renga-deployer:latest                   "./docker-entrypoi..."   3 minutes ago       Up 3 minutes               0.0.0.0:32977->5000/tcp                                      renga_deployer_1
c3b49b2d9ef8        rengahub/renga-authorization:latest              "bin/renga-authori..."   3 minutes ago       Up 3 minutes               0.0.0.0:32985->9000/tcp                                      renga_resource-manager_1
014f24cce31a        rengahub/renga-graph-init:latest                 "bin/renga-graph-init"   3 minutes ago       Exited (0) 2 minutes ago                                                                renga_graph-init_1
2c55710f3f5e        rengahub/renga-graph-navigation-service:latest   "bin/renga-graph-n..."   3 minutes ago       Up 3 minutes               0.0.0.0:32971->9000/tcp                                      renga_graph-navigation_1
de2d7e89b7ac        rengahub/renga-graph-mutation-service:latest     "bin/renga-graph-m..."   3 minutes ago       Up 3 minutes               0.0.0.0:32982->9000/tcp                                      renga_graph-mutation_1
cf7aaf78bf36        rengahub/renga-graph-typesystem-service:latest   "bin/renga-graph-t..."   3 minutes ago       Up 3 minutes               0.0.0.0:32983->9000/tcp                                      renga_graph-typesystem_1
6d8607e71e0c        renga_keycloak                                   "/data/docker-entr..."   3 minutes ago       Up 3 minutes               0.0.0.0:32974->8080/tcp                                      renga_keycloak_1
41f0da5220b6        cassandra:2.1.9                                  "/docker-entrypoin..."   3 minutes ago       Up 3 minutes               7000-7001/tcp, 7199/tcp, 9042/tcp, 0.0.0.0:32969->9160/tcp   renga_cassandra_1
da3bee5cb114        postgres:9.6                                     "docker-entrypoint..."   3 minutes ago       Up 3 minutes               0.0.0.0:32967->5432/tcp                                      renga_db_1
`

**Comment by rokroskar** [comment] 2018-05-16 11:46
Hi @stephan271 thanks for the report -- note that the current version of the platform is in the `development` branch and we are currently in the process of making that the default master branch. Is there a reason you running the "legacy" platform? If not, I suggest you either a) wait a week until we move things to `master` and clean up the docs or b) try out the `development` branch.

**Comment by stephan271** [comment] 2018-05-16 12:21
With the development branch the "make start" commands ends with:

building singleuser
Step 1/12 : ARG PLATFORM_VERSION=latest
ERROR: Service 'singleuser' failed to build: Please provide a source image with `from` prior to commit
make: *** [docker-compose-up] Error 1

**Comment by rokroskar** [comment] 2018-05-16 12:39
I can't reproduce this -- can you make sure you are on commit 5a238f1?

**Comment by stephan271** [comment] 2018-05-16 13:54
Yes, I am:
 git branch --all
* development
  master
...

git log
commit 5a238f149e2dc5906fbcf2a0371dced323821893
Author: Chandrasekhar Ramakrishnan <cramakri@ethz.ch>
Date:   Mon May 14 15:57:14 2018 +0200

    Changed the order in which referenced targets were run in the start target: register-gitlab-user-token needed to run before targets that require the token.

**Comment by rokroskar** [comment] 2018-05-16 15:47
what are the contents of the `.env` file?

**Comment by stephan271** [comment] 2018-05-17 06:16
`DOCKER_NETWORK=review
DOCKER_PREFIX=rengahub/
DOCKER_REPOSITORY=rengahub/
GITLAB_CLIENT_SECRET=dummy-secret
GITLAB_REGISTRY_URL=http://gitlab.renga.build:5081
GITLAB_RUNNERS_TOKEN=0d382523030a9ab74689100c16ebc0a93d0f244736810bd8a9337481fa534e8b
GITLAB_TOKEN=dummy-secret
GITLAB_URL=http://gitlab.renga.build
JUPYTERHUB_CLIENT_SECRET=dummy-secret
JUPYTERHUB_CRYPT_KEY=575197ce7f18a12ad5c2478dfd63c6d0dd325634d9cec95c0d0485f184630852
JUPYTERHUB_URL=http://jupyterhub.renga.build
KEYCLOAK_URL=http://keycloak.renga.build:8080
PLATFORM_DOMAIN=renga.build
PLATFORM_VERSION=development
PLAY_APPLICATION_SECRET=ab56d07d3f09a7de01855d39139904b37a0ee006739cb3f94aa2736b7f15508f
RENGA_ENDPOINT=http://renga.build
RENGA_UI_URL=http://renga.build
`

**Comment by stephan271** [comment] 2018-05-18 07:28
docker --version
Docker version 1.13.1, build 774336d/1.13.1

**Comment by rokroskar** [comment] 2018-05-18 11:12
it looks to me like the `ARG` option is not supported in docker CS 1.13.1. It was added in 17.06.1-ee and  17.05.0-ce. My understanding is that EE replaces CS docker but I could be wrong. See the release notes [here](https://docs.docker.com/ee/engine/release-notes/) and [here](https://docs.docker.com/release-notes/docker-ce/). It's possible that it's been backported in some newer release. Could you try [upgrading](https://docs.docker.com/cs-engine/1.13/upgrade/)?

**Comment by rokroskar** [comment] 2018-05-24 08:36
@stephan271 it seems like the original issues have been addressed -- I will close this for now but if you would like to continue discussion please feel free to reopen.

**Closed by rokroskar** 2018-05-24 08:36 UTC
