### ISSUE TITLE
helm alternatives

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku#671] opened 2019-10-04 08:22 UTC
Helm is intended to be a package manager for K8s. But its use as a devops/deployment tool is quite lacking. A year ago there were not many alternatives, but a lot of projects have been created in the meantime, either building on top of helm or replacing it.

In light of this, we should reconsider our tooling and see if there's any alternative better suited to our use cases.

Shortcomings of helm (A bit nit-picky and not everything here has to be addressed by an alternative :wink:  ):
- YAML file aren't DRY and there's not a lot of support for reusing definitions, which leads to a lot of duplication and difficulties in maintaining the code. Plus it's very verbose and hard to read, especially for newcomers.
- The `values.yaml` cannot be templated. It is impossible to e.g. use `.Release.Name` in the `values.yaml`, making it difficult for resources (or resources in subcharts) to refer to other resources which have dynamic names. For instance, a helm secret with a name of `{{ template "renku.fullname" . }}-secret` can't be passed to the `existingSecret` value of the keycloak subchart.
- The previous point means that we are entirely dependent on subchart  developers to add support to their chart for customizing (Passing values through the `tpl` function or allowing `extraEnv` to be set). This means we can only change what is intended to be changed by the chart developer, i.e. what they thought of when creating the charts, making it difficult to customize things when they did not envision our use cases (other than copying their chart and maintaining it ourselves).
- You get a single `values.yaml` for all your needs (There are some options to use more than one file with cmd flags, but the implementation is clunky and hard to use for users), which in many cases is too restrictive for actual devops needs.
- The way subcharts are handled means that a single chart without dependencies might work well enough, but having subcharts, subsubcharts etc., it quickly becomes unwieldy and a dependency hell, it's not obvious what need to be set on a subchart, some breaking changes to a subchart might go unnoticed (e.g. a subchart renames a value entry, we don't rename it in our `values.yaml`, so the default value gets used, things break but it's not obvious why they break)
- Deployments generally don't depend on the current state of the application. There's no way to deploy depending on what is already deployed. In cases where a change to one resource necessitates a reload of another (but unchanged) resource, you need hacks to force the restart, making upgrades difficult to do  and leaving a lot of room for bugs to creep into existing deployments on upgrade.
- More generally, helm doesn't really support lifecycle management of complex deployments and different environments. Workarounds/hacks and manual workflows are needed for something that should ideally be handled by tooling instead. 
- Bugs/typos in charts are very hard to spot, with sometimes borderline unreadable error messages.
- Bad user interaction. You run the command, wait a bit and maybe something didn't work. There's no way to provide feedback to the user like printing warnings, prompting for missing values, offering the user choices, no native input validation (I can set `serverOptions.cpu_request.default` to -100 and helm will happily apply it, writing validations for this in helm charts gets quite clunky, especially dynamic validations). 
- Go tpl/sprig is quite limited in scope and writing more than simple `| b64enc | quote` style code gets unmaintainable quickly. It lacks all the basic tools that usual programming has (Debugging, tests, etc.) and its syntax is not that usable for complex scripting. In a similar vein, the scripting has no regards for the structure and semantics of yaml itself. It should not be up to the developer to make sure that the produced yaml is syntactically valid!. Basically it doesn't really separate representation and code. If resources were objects in a programming language instead, you could work with them in a safe way, a compiler would catch illegal assignments, and indentation would be a non-issue as it would be automatically done on rendering.

Things helm does well:
- Preexisting charts for many applications, making it easy to get basic deployments.
- Rancher (and other platforms) integrations that allow one-click deployments - which they tend to work OK overall, but sometimes fail specifically due to helm/yaml quirks.
- No programming experience needed (at least in the ideal case) 
- Works well for charts without variability, applications that don't need a lot of customization and have a single, one size fits all, configuration.
- It is popular, which is a good thing in any tool
- It's a very thin layer on top of k8s, making it easy to set up and get started with.
- Open-source and can be used by anyone* (*terms and cluster-limitations may apply)

Ideally, an alternative to helm would still allow us to use helm charts, allowing for gradual replacement, but at the same time give us more powerful tools to deal with our complex use cases and increased ability to customize existing charts. And an alternative should also be usable by anyone (for free) without too much hassle (Ideally, install a tool, clone a repo, run a command, done).

A non-exhaustive list of possible alternatives:

- terraform (k8s or helm provider?)
- pulumi (k8s or helm provider?)
- helmfile (+helm)
- kustomize (together with helm?)
- Operator Framework (k8s or helm operators?)
- Ship
- JSonnet
- Kapitan
- hm, helm 3 (as a minimum, it solves the sanity checking via JSON schema based validation, #655)

Feel free to look for others.

We should evaluate which, if any, of these tools fit our workflow and use cases and then make a decision on whether to keep using helm or switching to one of these.

**Comment by ableuler** [comment] 2019-10-04 09:10
Thanks a lot @Panaetius for this detailed description of the problem at hand. One aspect that I would like to take into account during this evaluation is the ease of deployments on various types on infrastructure, ranging from our own K8s clusters built on open stack through managed k8s clusters of major cloud providers to openshift. The latter seems to be the container platform of choice at SWITCH, which - I we manage to do a good job - could make it relatively easy for academic institutions in Switzerland to run their own Renku instance.

**Comment by fgeorgatos** [comment] 2019-10-04 09:26
The low hanging fruit for 1-click deployments *today*, should be `rancher+openstack driver+helm`: I have done the PoC and it appears to work reasonably - once rancher node templates are defined. 

If that is a longer term good solution, is of course a different challenge. Big applause for raising this.

**Comment by Panaetius** [comment] 2019-10-04 12:25
Andreas brought up the idea of defining a minimal viable deployment that covers what's important to us. Then we can see about implementing this in the different options to give us an idea of how well they fit.

Proposal:
- Deployment with 2 standard pods such as nginx
- Service with a LoadBalancer exposing the deployment
- Share some value in multiple places, e.g. set a string in the tool and use it as `metadata.labels` in the deployment and service.
- Additionally, set a label on the Deployment and refer to that label (include it) in the labels of the Service (i.e. check if resources can refer to and depend on each other)
- a Secret with a randomly generated password (and a generated resource name, e.g. `{{.Release.Name}}-secret` if we were using helm. If the provider has some secret specific abstraction, use that instead.
- use the generated Secret for nginx as described here: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
- Return URL, username and password of the deployment to the user. Check that the login works.

*(optionally, if helm is supported):*
- include a subchart
- try and modify the subchart in a way that is not usually supported, e.g. rename a resource that has no support to be renamed via helm (-values.yaml)

*(optionally, for secrets stuff requirements):*
- Increase the number of replicas or change ports or some other small change and redeploy, check that everything works and password is still valid
- Change password and redeploy, check that new password is now needed

Feedback is welcome, if we have a nice test case we can start trying it out in different tools and see what some of the benefits and drawbacks of each of them are.

**Comment by pameladelgado** [comment] 2019-10-04 12:37
thanks @Panaetius and @ableuler for putting this together.
I think this minimal deployment case covers what we need. Do we maybe want to check for other k8s resources like ConfigMaps, Registries, Certificates?

**Comment by Panaetius** [comment] 2019-10-04 13:22
I think checking that all kinds of k8s resources are supported is important (by reading the respective docs), but doesn't have to necessarily be part of the minimal deployment case. If one of the resources has some special quirk and is something we use, i.e. it behaves differently that other resources (from a deployment point of view), we can add a test for it. Fir instance,  `ConfigMap`s should generally work the same as `Secret`s, so I'm not sure both have to be tested.

**Comment by Panaetius** [comment] 2019-10-04 14:08
Additionally, we should also judge our own impression of it, e.g. on a scale from 1 to 5 how good are:
- Popularity / Community Size
- Documentation
- Ease of use
- Configuration Language/Code syntax
- Verbosity of configuration/code
- CLI toolchain
- Setup
- Composability/reusability inside code/configuration
- Packaging/Reuse of whole code/deployments (like charts & subcharts in helm)
- Extensibility
- Interoperability with other common tools
- Support for different cloud providers, especially OpenShift
- Support
- License

**Comment by Panaetius** [comment] 2019-10-16 12:32
**Pulumi (Python)**

test deployment/setup can be found here: https://github.com/Panaetius/pulumi-test

- Popularity / Community Size (*3*): Ok-ish. Seen it recommended in several places, 3.7k stars on github vs. 19.1k for terraform
- Documentation (*3*): Basic documention is decent, lacks examples in most cases or only has examples for typescript instead of python
- Ease of use (*5*): Quite easy to setup, no crazy syntax or complicated commandline commands needed
- Configuration Language/Code syntax (*5*): Python, everything makes sense, classes map directly to k8s resources
- Verbosity of configuration/code (*4*): very little repetition, sane defaults, mostly only need to set what actually needs setting
- CLI toolchain (*4*): pulumi up/destroy works really well, error messages are readable and easy to work with. Creates resources in order, waits for creation and ing eneral behaves intelligently. Some issues with errors when using helm (Only says `helm command [...] returned with status code 1`, still easy to debug. Annoying that it still waits for pods to come up even if there was an error in deploying. It's always very clear what will be done and a detailed diff can be viewed before applying any changes.
- Setup (*5*): Simple installation with a script
- Composability/reusability inside code/configuration (*5*): it's all python code, so custom classes can be created for everything as needed, it allows to specify transformations for helm charts to modify them in place, basically any software design patterns can also be applied to pulumi deployments
- Packaging/Reuse of whole code/deployments (like charts & subcharts in helm)(*4*): Applications can be set up as stacks, for different environments, and one stack can depend on another stack, with pulumi taking care of managing that everything is up. it has to be done in code though and is kind of implicit, which is not as nice as having a requirements file.
- Extensibility (*5*): Sourcecode can be freely extended and is set up in a way that this should be easy to do in most cases.
- Interoperability with other common tools (*5*): Works well with helm, 
- Support for different cloud providers, especially OpenShift(*4*): Supports most common cloud providers (Google, AWS, Azure, OpenStack, apparently OpenShift support should not be too much effort, but it's not currently supported: https://github.com/pulumi/pulumi-kubernetes/issues/214 
- Support(*4*): Most github issues are replied to within 1 hour to 1 day, with helpful comments and tasks. There's also a community slack. But there's not a lot of SO answers, blog posts or similar 3rd party resources
- License (*5*): Apache 2.0, FOSS

**Overall Score: 4.36**

**Comment by Panaetius** [comment] 2019-10-31 08:04
Good Question. Actually I need to adjust my Pulumi scores as I didn't really settle on a scoring system and just went with what it felt like. But for Helmfile I went with the approach of 1 = a lot worse than what we currently have, 2 = worse, 3 = the same, 4 = better, 5= a lot better (So 3 = basically the same as having Helm with an Umbrella chart).

**Comment by ableuler** [comment] 2019-11-03 16:44
### Operator framework

The K8s API can be extended by defining custom resources. The operator pattern describes the use of such a custom resource definition (CRD) together with a controller (operator) which manages the custom resource. By following the operator pattern we could therefore deploy a Renku resource with the necessary parameters given as resource `spec` directly to the cluster using the K8s API.

While operators can be used to deploy "simple" applications, they mostly shine in cases where managing a running instance of the application (scaling, upgrading, etc) includes complicated logic which in the absence of operators often needs to be carried out manually (such as stateful applications which need to be highly available).

The [operator SDK](https://github.com/operator-framework/operator-sdk) is used to build operators in practice. The SDK provides 3 flavours of operators: **go**, **ansible** and **helm**.

**helm operators**
Creating an operator from an existing helm chart is trivial. The content of the `values.yaml` file from the chart is copied into the `spec` section of a manifest file describing the custom (Renku) resource. Editing the specs of the manifest file before applying it to the cluster is the equivalent of editing a deployment specific `some-deployment-values.yaml` file. The main added value over plain helm is the absence of tiller (which helm 3 also gets rid of). Unfortunately, helm operators won't help with the biggest pain point of our current helm deployment (the fact that we have to provide values in the umbrella chart in exactly the way they are consumed by the sub-chart, eg Jupyterhub). Therefore, I would discard helm-based operators as a viable alternative to our current deployment right away.

**go operators**
These could also be considered "plain" operators. They allow and require the most fine grained control over the creation, modification and deletion of the K8s resources belonging to an application. While the SDK helps with the boilerplate, the entire logic (ie which resources to watch, calls to the k8s API, etc) have to be coded up explicitly. I did not reproduce the minimal example from @Panaetius through a go operator because I believe that go operators are not a serious contender in this evaluation. [This example](https://medium.com/@shubhomoybiswas/writing-kubernetes-operator-using-operator-sdk-c2e7f845163a) gives a taste of the verbosity and syntax of a go operator. 

**Summary** 
While helm operators are not much of an improvement over the current situation, most of the necessary logic that would have to be implemented in a go operator (resource templating, k8s API calls, ...) is already abstracted away by other solutions which are thus much more convenient for our use case.

**Comment by ableuler** [comment] 2019-11-05 16:19
> test deployment/setup can be found here: https://github.com/Panaetius/pulumi-test

Does [this](https://github.com/Panaetius/pulumi-test/blob/52c5876f3181a2e8e014802b9edb72309207936c/__main__.py#L90) actually need tiller to run inside the cluster?

**Comment by Panaetius** [comment] 2019-11-06 07:57
> > test deployment/setup can be found here: https://github.com/Panaetius/pulumi-test
> 
> Does [this](https://github.com/Panaetius/pulumi-test/blob/52c5876f3181a2e8e014802b9edb72309207936c/__main__.py#L90) actually need tiller to run inside the cluster?

No, from https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/helm/v2/ :
> Chart does not use Tiller. The Chart specified is copied and expanded locally; the semantics are equivalent to running helm template and then using Pulumi to manage the resulting YAML manifests. Any values that would be retrieved in-cluster are assigned fake values, and none of Tiller’s server-side validity testing is executed

**Comment by Panaetius** [comment] 2019-11-06 09:08
**kustomize**

Not going to do the full test as I don't think this is suitable. Basically kustomize just lets you write regular k8s resource manifests and then have patch files that modify those resources before using `kubectl apply`. Different patches for different environments are possible, but there's no scripting/logic of any kind. One could imagine using `helm template` followed by `kustomize`and then `kubectl apply` but that doesn't help with operations at all and doesn't alleviate all issues with helm, it'd just allow us to modify third party charts before deploying. So I think this isn't a viable solution.

**Comment by Panaetius** [comment] 2019-11-06 09:55
**Ship**

Basically just a nice UI to help with the creation of `kustomize` patches on top of helm charts, so the `kustomize` review applies. Would improve upon our current workflow but not by a lot and doesn't help a lot with the limitations of helm.

**Comment by Panaetius** [comment] 2019-11-06 12:04
**Kapitan / JSonnet**

Reviewing Kapitan and JSonnet together as JSonnet ist just a powerful templating language (and KSonnet has been discontinued), but nothing else. Kapitan uses JSonnet for templating.

Kapitan is the same as helm, as in you write templates and values files and those get rendered to deploy the application. Instead of Sprig/Go templating, it uses JSonnet, Jinja2 and Kadet for templating, which are a bit more expressive/generic. It allows multiple values files in a hierarchy and with customization for different enviroments. And it doesn't have a server component like Tiller, using `kubectl apply` instead. It also includes separate secret management with GPG encryption (and secret generation if a secret doesn't exist). So in many ways it's like helm but done right. It doesn't have the package manager aspect of helm though and doesn't support helm charts. 

I think it does a lot of things right that helm does wrong, but has its own issues. Terraform and Pulumi are probably more comprehensive solutions.

- Popularity / Community Size (*2*): Ok-ish. 1k stars on github.
- Documentation (*4*): Documentation is very readable and well structured.
- Ease of use (*4*): Simple CLI interface, not that many commands, pretty straightforward.
- Configuration Language/Code syntax (*4*): Jinja2 and JSonnet are both nice templating language.
- Verbosity of configuration/code (*4*): Allowing multiple values files that get combined in a hierarchical fashion is really nice. Still quite verbose as you need the whole K8s manifest and add varables there.
- CLI toolchain (*2*): `kapitan compile` compiles all the templates and values file together for each deployment (and runs schema validation, if available) into one folder per deployment, which can then be deployed with `kubectl apply`. No functionality for managing/upgrading releases, just `kubectl apply`, so no way to rollback etc.
- Setup (*5*): `pip install kapitan`
- Composability/reusability inside code/configuration (*4*): Jsonnet allows importing templates from other templates, so manifests can be reused/composed. Additionally, value files can be set up in a hierarchy with files higher in the hierarchy overriding lower files, this allows base values files that get overridden for different deployments etc.
- Packaging/Reuse of whole code/deployments (like charts & subcharts in helm)(*2*): A Kapitan deployment can load values from external dependencies, like a github repo, but there's no concept of having a package that can just be included in another application unless done manually with JSonnet.
- Extensibility (*4*): Written in Python.
- Interoperability with other common tools (*2*): Supports helm (by calling `helm template`) but doesn't support the `requirements.yaml`, so doesn't pull subcharts. Plus values for helm have to be specified separately without all the values magic normally available. Helm support is in alpha stage. 
- Support for different cloud providers, especially OpenShift(*3*): Only supports K8s
- Support(*5*): Github issues usually replied to within a couple of hours, slack and mailing list available.
- License (*5*): Apache 2.0

**Overall Score: 3.57**

**Comment by Panaetius** [comment] 2019-11-07 13:24
**Terraform**

Doesn't really need an introduction. Test repo at https://github.com/Panaetius/terraform-test



- Popularity / Community Size (*5*): Most popular solution right now.
- Documentation (*4*): Documentation is very readable and well structured.
- Ease of use (*4*): Simple CLI interface, not that many commands, pretty straightforward.
- Configuration Language/Code syntax (*4*): HCL is easy enough, though it's something more to learn and has a few idiosyncracies that are not immediately obvious from experience with other programming languages.
- Verbosity of configuration/code (*5*): Pretty reusable, whole blocks of definitions can be reused and there seem to be mostly sane defaults for K8s values.
- CLI toolchain (*4*): Works very well and does intelligent execution plan. Only reason it's a 4 and not a 5 is that helm is excluded from benefiting from most of this
- Setup (*3*): Zipped binary
- Composability/reusability inside code/configuration (*5*): Can be spread over multiple `*.tf` files and individual blocks of configuration can be reused in other blocks
- Packaging/Reuse of whole code/deployments (like charts & subcharts in helm)(*5*): The Module system is nice and easily allows for reuse
- Extensibility (*4*): Written in Go and supports Go plugins. Should probably be a 3.5 rating as Python is easier :wink:
- Interoperability with other common tools (*4*): Supports many tools/providers, though helm support is not that great.
- Support for different cloud providers, especially OpenShift(*4*): Supports pretty much everything, except OpenShift (though it does somewhat work using the regular k8s provider)
- Support(*5*): Github issues usually replied to within a couple of hours, Gitter and mailing list available.
- License (*5*): Mozilla Public License 2.0

**Overall Score: 4.35**


Some thoughts: Biggest plus is obviously the support&adoption, it is the biggest player out there. But i felt working with pulumi was more comfortable, I had fewer roadblocks where I wasn't sure how to proceed or what I did wrong, since I didn't have to learn a new language. Helm support in terraform seems mediocre at best.

Issues I've come across:

- Helm
    - Needs tiller (not an issue with helm 3).
    - Values are specified either as multiline yaml string, or they have to be declared `flat`, i.e. for each value you must use the full path to the value as key like `'metadata.labels.name'='foo'` which leads to a lot of duplication/clutter and has the potential to lead to bugs.
    - Can't Output values of resources in K8s, only values of the chart definition. I.e. it's impossible to output the ip of a pod created by helm. One would have to use the k8s provider to access the cluster to get that information.
    - Charts can't be modified beyond specifying values.yaml values.
    - Charts a treated as a black box and just handed to helm, Terraform doesn't know anything about the resources created or what the chart does etc. Resources created by helm charts are not first class citizens.
- Kubernetes
    - The naming is different to the official k8s naming, e.g. `service_name` instead of `serviceName` or specifying multiple `volume` entries instead of having a `volumes` property that is a list.
    - doesn't support $PATH style kube config loading https://github.com/terraform-providers/terraform-provider-kubernetes/pull/511
    - namespace has to be specified manually everywhere it applies.
        
- in general
    - Sometimes not really clear when to use `name = {` and when `name {` though the error produced helps.
    - the diff shown is very long instead of just showing changed lines, making it easy to overlook an error.
    - it doesn't know how to handle values added by rancher, e.g. `field.cattle.io/publicEndpoints` annotation. Updates the resource and removes that part every time even though nothing changed in the terraform definitions.

**Comment by ableuler** [comment] 2020-05-08 18:58
Closing this issue in favour of the epic #1078 and its issues.

**Closed by ableuler** 2020-05-08 18:58 UTC
Labels: enhancement
